export const TABBAR =[{
			iconPath: "/static/ic_depart.png",
			selectedIconPath: "/static/ic_depart_focus.png",
			text: '航班',
			count: 0,
			customIcon: false,
			pagePath: "/pages/flight/index",
		},
		{
			iconPath: "/static/ic_collection.png",
			selectedIconPath: "/static/ic_collection_focus.png",
			text: '关注',
			count: 0,
			customIcon: false,
			pagePath: "/pages/follow/index",
		},
		{
			iconPath: "/static/ic_task.png",
			selectedIconPath: "/static/ic_task_focus.png",
			text: '任务',
			count: 0,
			customIcon: false,
			pagePath: "/pages/tasks/index",
		},
		{
			iconPath: "/static/ic_im_normal.png",
			selectedIconPath: "/static/ic_im_focus.png",
			text: '消息',
			count: 0,
			customIcon: false,
			pagePath: "/pages/message/index",
		},
	]
