  /*
   *  名称: 报文
   *  功能: 报文key
   */
  
   export const MESSAGEKEYARRAY={
        ZSAM: [
          'ACDM.FLIGHTSCHEDULE.ZSAM.FLIGHTMOVEMENT.ADD',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.FLIGHTARCHIVE',
          'ACDM.FLIGHTSCHEDULE.ZSAM.FLIGHTMOVEMENT.DELETE',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.ALLOWBOARDING',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.BOARDINGCLOSED',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.BOARDINGOPEN',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.COBTUPDATE',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.FINALBOARDING',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.ARRDIVERSION',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.CANCEL',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.DELAY',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.ARRIVALLAND',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.DEPARTREVERSAL',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.TAKEOFF',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.LINKEDFLIGHTUPDATE',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.CODESHAREUPDATE',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.TRANSITBOARDING',
          'ACDM.FLIGHTSCHEDULE.ZSAM.FLIGHTMOVEMENT.UPDATE',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.HOMEARRIVAL',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.ARRIVETONEXT',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.RETURNTOPORT',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.FLIGHTRELATION', // 关联
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.FLIGHTSPLIT', // 拆分
          'ACDM.FLIGHTSCHEDULE.ZSAM.TOBT.UPDATE',
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.CANCELLATIONOFBOARDING', // 取消登机
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.CANCELANDENDOFBOARDING', // 取消登机结束
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.UPDATEGATE', // 登机口变更
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.UPDATESTAND', // 机位变更
          'ACDM.FLIGHTSCHEDULE.ZSAM.ACTIVITY.VIPUPDATE' // vip变更
        ],
        ZSFZ: [
          'ACDM.FLIGHTSCHEDULE.ZSFZ.TOBT.UPDATE', // tobt变更
          'ACDM.FLIGHTSCHEDULE.ZSFZ.ACTIVITY.VIPUPDATE' // vip变更
        ]
      }